# docker-compose.yaml for stage0 developer edition

services:
  ##################################
  # Backing Services 
  ##################################
  # MongoDB backing service (single node replica set)
  mongodb:
    image: mongo:7.0.5
    ports:
      - 27017:27017
    extra_hosts:
      - "mongodb:127.0.0.1"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    profiles:
      - all
      - mongodb-api
      - mongodb
      - search-api
      - search
      - cat-api
      - cat
      - fran-api
      - fran
      - paul-api
      - paul
      - sam-api
      - sam
      - identity-api
      - identity

  ##################################
  # Elasticsearch backing service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - "xpack.security.enabled=false"
      - "action.destructive_requires_name=false"
      - "network.bind_host=0.0.0.0"
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    profiles:
      - all
      - search-api
      - search

  ##################################
  # Kibana for Elasticsearch service
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2
    ports:
      - 5601:5601
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: c69548d9027afcf4d55146b1d425a9f4c69548d9027afcf4d55146b1d425a9f4
    profiles:
      - all
      - search-api
      - search

  ##################################
  # Zookeeper manager for Kafka cluster
  zookeeper:
    image: zookeeper:3.9.2
    ports:
      - "2181:2181"
    profiles:
      - all
      - kafka-connect
      - identity-api
      - identity

  ##################################
  # Kafka event bus
  kafka:
    image: confluentinc/cp-kafka:7.3.0  
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:19092
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
    depends_on:
      - zookeeper
    profiles:
      - all
      - kafka-connect
      - identity-api
      - identity

  ##################################
  # Kafka Connector (Custom connector with Mongo and Elastic plugins)
  kafka_connect:
    image: ghcr.io/agile-learning-institute/stage0_kafka_connect:latest
    ports:
      - "9093:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:19092
      CONNECT_REST_ADVERTISED_HOST_NAME: localhost
      CONNECT_GROUP_ID: "mongo-elastic-sync"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
    depends_on:
      kafka:
        condition: service_started
    profiles:
      - all
      - kafka-connect
      - identity-api
      - identity

  ##################################
  # MongoDB configuration Service
  ##################################
  mongodb_api:
    image: ghcr.io/agile-learning-institute/stage0_mongo_api:latest
    restart: no
    ports:
      - 8081:8081
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongodb:27017/?replicaSet=rs0
      AUTO_PROCESS: True
      LOAD_TEST_DATA: True
    depends_on:
      mongodb:
        condition: service_healthy
    profiles:
      - all
      - mongodb-api
      - mongodb

  mongodb_spa:
    image: ghcr.io/agile-learning-institute/stage0_mongodb_spa:latest
    restart: no
    environment:
      MONGODB_API_HOST: mongodb_api
      MONGODB_API_PORT: 8081
    ports:
      - 8082:8082
    depends_on:
      - mongodb_api
    profiles:
      - all
      - mongodb

  ##################################
  # Search Service with MongoDB Ingest features
  ##################################
  search_api:
    image: ghcr.io/agile-learning-institute/stage0_search_api:latest
    restart: no
    ports:
      - 8083:8083
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongodb:27017/?replicaSet=rs0
      ELASTIC_CLIENT_OPTIONS: '{"node":"http://elasticsearch:9200"}'
    depends_on:
      mongodb_api:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    profiles:
      - all
      - search-api
      - search

  search_spa:
    image: ghcr.io/agile-learning-institute/stage0_search_spa:latest
    restart: no
    environment:
      SEARCH_API_HOST: search_api
      SEARCH_API_PORT: 8083
    ports:
      - 8084:8084
    depends_on:
      - search_api
    profiles:
      - all
      - search

  ##################################
  # Cat the Customer Service Representative
  ##################################
  cat_bot:
    image: ghcr.io/agile-learning-institute/stage0_cat_bot:latest
    restart: no
    ports:
      - 8085:8085
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongodb:27017/?replicaSet=rs0
    depends_on:
      mongodb_api:
        condition: service_started
    profiles:
      - all
      - cat-bot
      - cat

  cat_spa:
    image: ghcr.io/agile-learning-institute/stage0_cat_spa:latest
    restart: no
    environment:
      CAT_BOT_HOST: cat_bot
      CAT_BOT_PORT: 8085
    ports:
      - 8086:8086
    depends_on:
      - cat_bot
    profiles:
      - all
      - cat

  ##################################
  # Fran the Design Thinking Facilitator
  ##################################
  fran_bot:
    image: ghcr.io/agile-learning-institute/stage0_fran_bot:latest
    restart: no
    ports:
      - 8087:8087
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongodb:27017/?replicaSet=rs0
    depends_on:
      mongodb_api:
        condition: service_started
    profiles:
      - all
      - fran-bot
      - fran

  fran_spa:
    image: ghcr.io/agile-learning-institute/stage0_fran_spa:latest
    restart: no
    environment:
      FRAN_BOT_HOST: fran_bot
      FRAN_BOT_PORT: 8087
    ports:
      - 8088:8088
    depends_on:
      - fran_bot
    profiles:
      - all
      - fran

  ##################################
  # Paul the Product Manager
  ##################################
  paul_bot:
    image: ghcr.io/agile-learning-institute/stage0_paul_bot:latest
    restart: no
    ports:
      - 8089:8089
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongodb:27017/?replicaSet=rs0
    depends_on:
      mongodb_api:
        condition: service_started
    profiles:
      - all
      - paul-bot
      - paul

  paul_spa:
    image: ghcr.io/agile-learning-institute/stage0_paul_spa:latest
    restart: no
    environment:
      PAUL_BOT_HOST: paul_bot
      PAUL_BOT_PORT: 8089
    ports:
      - 8090:8090
    depends_on:
      - paul_bot
    profiles:
      - all
      - paul

  ##################################
  # Sam the Support Engineer
  ##################################
  sam_bot:
    image: ghcr.io/agile-learning-institute/stage0_sam_bot:latest
    restart: no
    ports:
      - 8091:8091
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongodb:27017/?replicaSet=rs0
    depends_on:
      mongodb_api:
        condition: service_started
    profiles:
      - all
      - sam-bot
      - sam

  sam_spa:
    image: ghcr.io/agile-learning-institute/stage0_sam_spa:latest
    restart: no
    environment:
      SAM_BOT_HOST: sam_bot
      SAM_BOT_PORT: 8091
    ports:
      - 8092:8092
    depends_on:
      - sam_bot
    profiles:
      - all
      - sam

  ##################################
  # Identity Service
  ##################################
  identity_api:
    image: ghcr.io/agile-learning-institute/stage0_identity_api:latest
    restart: no
    ports:
      - 8093:8093
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongodb:27017/?replicaSet=rs0
    depends_on:
      mongodb_api:
        condition: service_started
      kafka_connect:
        condition: service_started
    profiles:
      - all
      - identity-api
      - identity

  identity_spa:
    image: ghcr.io/agile-learning-institute/stage0_identity_spa:latest
    restart: no
    environment:
      IDENTITY_API_HOST: identity_api
      IDENTITY_API_PORT: 8093
    ports:
      - 8094:8094
    depends_on:
      - identity_api
    profiles:
      - all
      - identity
