version: '3.8'

services:
  ##################################
  # Backing Services 
  ##################################
  # MongoDB backing service (single node replica set)
  mongodb:
    image: mongo:7.0.5
    ports:
      - 27017:27017
    extra_hosts:
      - "mongodb:127.0.0.1"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    profiles:
      - all
      - kafka-connect
      - mongo-only
      - elasticsearch
      - elasticonly
      - mongo
      - mongo-api
      - search 
      - search-api
      - admin
      - admin-api
      - apprentice
      - apprentice-api
      - mentor
      - mentor-api
      - identity
      - identity-api

  ##################################
  # Elasticsearch backing service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - "xpack.security.enabled=false"
      - "action.destructive_requires_name=false"
      - "network.bind_host=0.0.0.0"
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    profiles:
      - all
      - kafka-connect
      - elasticsearch
      - elasticonly
      - search
      - search-api

  ##################################
  # Zookeeper manager for Kafka cluster
  zookeeper:
    image: zookeeper:3.9.2
    ports:
      - "2181:2181"
    profiles:
      - all
      - kafka-connect

  ##################################
  # Kafka event bus
  kafka:
    image: confluentinc/cp-kafka:7.3.0  
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:19092
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
    depends_on:
      - zookeeper
    profiles:
      - all
      - kafka-connect

  ##################################
  # Kafka Connector (Custom connector with Mongo and Elastic plugins)
  kafka-connect:
    image: ghcr.io/agile-learning-institute/mentorhub-kafka-connect:latest
    ports:
      - "9093:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:19092
      CONNECT_REST_ADVERTISED_HOST_NAME: localhost
      CONNECT_GROUP_ID: "mongo-elastic-sync"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
    depends_on:
      kafka:
        condition: service_started
    profiles:
      - all
      - kafka-connect

  ##################################
  # Mongo Database Configuration Utilities
  ##################################
  stage0-mongo-api:
    image: ghcr.io/agile-learning-institute/stage0-mongo-api:latest
    restart: no
    ports:
      - 8080:8080
    environment:
      CONNECTION_STRING: mongodb://mongodb:27017/?replicaSet=rs0
    depends_on:
      mongodb:
        condition: service_healthy
    profiles:
      - all
      - mongo
      - mongo-api
  stage0-mongo-spa:  
    image: ghcr.io/agile-learning-institute/stage0-mongo-spa:latest
    restart: no
    environment:
      API_HOST: stage0-mongo-api
      API_PORT: 8080
    ports:
      - 8081:8081
    depends_on:
      - stage0-mongo-api
    profiles:
      - all
      - mongo

  ##################################
  # Search API with MongoDB Ingest features
  ##################################
  stage0-search-api:
    image: ghcr.io/agile-learning-institute/stage0-search-api:latest
    restart: no
    ports:
      - 8082:8082
    environment:
      CONNECTION_STRING: mongodb://mongodb:27017/?replicaSet=rs0
      HOST: stage0-searchdb
      ELASTIC_CLIENT_OPTIONS: '{"node":"http://elasticsearch:9200"}'
    depends_on:
      stage0-mongo-api:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    profiles:
      - all
      - search
      - search-api
  stage0-search-spa:
    image: ghcr.io/agile-learning-institute/stage0-search-spa:latest
    restart: no
    environment:
      API_HOST: stage0-search-api
      API_PORT: 8082
    ports:
      - 8083:8083
    depends_on:
      - stage0-search-api
    profiles:
      - all
      - search

  ##################################
  # Admin Service (Users and Partners)
  ##################################
  stage0-admin-api:
    image: ghcr.io/agile-learning-institute/stage0-admin-api:latest
    restart: no
    ports:
      - 8084:8084
    environment:
      CONNECTION_STRING: mongodb://mongodb:27017/?replicaSet=rs0
    depends_on:
      stage0-mongo-api:
        condition: service_started
    profiles:
      - all
      - admin
      - admin-api
  stage0-admin-spa:
    image: ghcr.io/agile-learning-institute/stage0-admin-spa:latest
    restart: no
    environment:
      API_HOST: stage0-admin-api
      API_PORT: 8084
    ports:
      - 8085:8085
    depends_on:
      - stage0-admin-api
    profiles:
      - all
      - admin

  ##################################
  # Apprentice Service (Curriculum and Encounters)
  ##################################
  stage0-apprentice-api:
    image: ghcr.io/agile-learning-institute/stage0-apprentice-api:latest
    restart: no
    ports:
      - 8086:8086
    environment:
      CONNECTION_STRING: mongodb://mongodb:27017/?replicaSet=rs0
    depends_on:
      stage0-mongo-api:
        condition: service_started
    profiles:
      - all
      - apprentice
      - apprentice-api
  stage0-apprentice-spa:
    image: ghcr.io/agile-learning-institute/stage0-apprentice-spa:latest
    restart: no
    environment:
      API_HOST: stage0-apprentice-api
      API_PORT: 8086
    ports:
      - 8087:8087
    depends_on:
      - stage0-apprentice-api
    profiles:
      - all
      - apprentice

  ##################################
  # Mentor Service (Topics, Paths, and Plans)
  ##################################
  stage0-mentor-api:
    image: ghcr.io/agile-learning-institute/stage0-mentor-api:latest
    restart: no
    ports:
      - 8088:8088
    environment:
      CONNECTION_STRING: mongodb://mongodb:27017/?replicaSet=rs0
    depends_on:
      stage0-mongo-api:
        condition: service_started
    profiles:
      - all
      - mentor
      - mentor-api
  stage0-mentor-spa:
    image: ghcr.io/agile-learning-institute/stage0-mentor-spa:latest
    restart: no
    environment:
      API_HOST: stage0-mentor-api
      API_PORT: 8088
    ports:
      - 8089:8089
    depends_on:
      - stage0-mentor-api
    profiles:
      - all
      - mentor

  ##################################
  # Identity Service
  ##################################
  stage0-identity-api:
    image: ghcr.io/agile-learning-institute/stage0-identity-api:latest
    restart: no
    ports:
      - 8090:8090
    environment:
      CONNECTION_STRING: mongodb://mongodb:27017/?replicaSet=rs0
    depends_on:
      stage0-mongo-api:
        condition: service_started
    profiles:
      - all
      - identity
      - identity-api
  stage0-identity-spa:
    image: ghcr.io/agile-learning-institute/stage0-identity-spa:latest
    restart: no
    environment:
      API_HOST: stage0-identity-api
      API_PORT: 8090
    ports:
      - 8091:8091
    depends_on:
      - stage0-identity-api
    profiles:
      - all
      - identity 